mirandathiago/lista-exercicios1-progwebII-2023

- resolucoes/2ano-matutino/emanuelle/parte1/q2/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte1/q2/index.php
- resolucoes/2ano-matutino/emanuelle/parte1/q2/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte1/q7/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte1/q7/index.php
- resolucoes/2ano-matutino/emanuelle/parte1/q7/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte2/q1/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte2/q1/index.php
- resolucoes/2ano-matutino/emanuelle/parte2/q1/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte2/q10/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte2/q10/index.php
- resolucoes/2ano-matutino/emanuelle/parte2/q10/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte2/q6/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte2/q6/index.php
- resolucoes/2ano-matutino/emanuelle/parte2/q6/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte2/q8/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte2/q8/index.php
- resolucoes/2ano-matutino/emanuelle/parte2/q8/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte3/q2/index.php
- resolucoes/2ano-matutino/emanuelle/parte3/q3/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte3/q3/index.php
- resolucoes/2ano-matutino/emanuelle/parte3/q3/resposta.php
- resolucoes/2ano-matutino/emanuelle/parte3/q6/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte3/q6/index.php
- resolucoes/2ano-matutino/emanuelle/parte3/q7/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte3/q7/index.php
- resolucoes/2ano-matutino/emanuelle/parte4/q1/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte4/q1/index.php
- resolucoes/2ano-matutino/emanuelle/parte4/q3/estilo.css
- resolucoes/2ano-matutino/emanuelle/parte4/q3/index.php
Questões Respondidas :
Parte1 :  2, 7
Parte2 : 1, 6, 8,10
Parte3 : 2, 3, 6, 7
Parte4 : 1, 3
> Entrega Final da Lista de Exercícios - Emanuelle Souza Pires

- resolucoes/2ano-matutino/raissa/parte1/q3/estilo.css
- resolucoes/2ano-matutino/raissa/parte1/q3/index.php
- resolucoes/2ano-matutino/raissa/parte1/q4/estilo.css
- resolucoes/2ano-matutino/raissa/parte1/q4/index.php
- resolucoes/2ano-matutino/raissa/parte2/q1/estilo.css
- resolucoes/2ano-matutino/raissa/parte2/q1/index.php
- resolucoes/2ano-matutino/raissa/parte2/q5/estilo.css
- resolucoes/2ano-matutino/raissa/parte2/q5/index.php
- resolucoes/2ano-matutino/raissa/parte2/q6/estilo.css
- resolucoes/2ano-matutino/raissa/parte2/q6/index.php
- resolucoes/2ano-matutino/raissa/parte2/q7/estilo.css
- resolucoes/2ano-matutino/raissa/parte2/q7/index.php
- resolucoes/2ano-matutino/raissa/parte3/q2/estilo.css
- resolucoes/2ano-matutino/raissa/parte3/q2/index.php
- resolucoes/2ano-matutino/raissa/parte3/q5/estilo.css
- resolucoes/2ano-matutino/raissa/parte3/q5/index.php
- resolucoes/2ano-matutino/raissa/parte3/q7/estilo.css
- resolucoes/2ano-matutino/raissa/parte3/q7/index.php
- resolucoes/2ano-matutino/raissa/parte3/q8/estilo.css
- resolucoes/2ano-matutino/raissa/parte3/q8/index.php
- resolucoes/2ano-matutino/raissa/parte4/q1/estilo.css
- resolucoes/2ano-matutino/raissa/parte4/q1/index.php
- resolucoes/2ano-matutino/raissa/parte4/q2/estilo.css
- resolucoes/2ano-matutino/raissa/parte4/q2/index.php
Eu fiz as questões 3 e 4 da parte 1; as questões 1, 5, 6 e 7 da parte 2; as questões 2, 5, 7 e 8 da parte 3; as questões 1 e 2 da parte 4.
> Entrega final da Lista de Exercícios - Raíssa Santos

- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte1/q10/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte1/q10/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte1/q7/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte1/q7/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q10/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q10/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q4/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q4/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q5/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q5/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q8/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte2/q8/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q1/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q1/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q10/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q10/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q5/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q5/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q8/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte3/q8/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte4/q1/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte4/q1/index.php
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte4/q2/estilo.css
- resolucoes/3ano-vespertino/MariaDeFatimaDeAlmeidaPortela/parte4/q2/index.php
- Parte 1: 7, 10
- Parte 2: 4, 5, 8, 10
- Parte 3: 1, 5, 8, 10
- Parte 4: 1, 2
> Entrega final da Lista de Exercícios - Maria de Fatima de Almeida Portela

- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte1/q3/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte1/q3/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte1/q4/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte1/q4/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q2/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q2/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q4/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q4/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q5/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q5/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q7/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte2/q7/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q10/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q10/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q2/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q2/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q3/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q3/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q7/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte3/q7/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte4/q1/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte4/q1/index.php
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte4/q2/estilo.css
- resolucoes/3ano-vespertino/eriklouhanmachadosilva/parte4/q2/index.php
##Questões Respondidas##
Parte 1:
-q3;
-q4;
Parte 2:
-q2;
-q4;
-q5;
-q7.
Parte 3: 
-q2;
-q3;
-q7;
-q10.
Parte 4:
-q1;
-q2.
> Entrega Final da Lista de Exercícios - Erik Louhan Machado Silva

- resolucoes/2ano-matutino/andreybonfim/parte1/q2/index.php
- resolucoes/2ano-matutino/andreybonfim/parte1/q2/resposta.php
- resolucoes/2ano-matutino/andreybonfim/parte1/q7/index.php
- resolucoes/2ano-matutino/andreybonfim/parte2/q1/index.php
- resolucoes/2ano-matutino/andreybonfim/parte2/q1/resposta.php
- resolucoes/2ano-matutino/andreybonfim/parte2/q2/index.php
- resolucoes/2ano-matutino/andreybonfim/parte2/q6/index.php
- resolucoes/2ano-matutino/andreybonfim/parte2/q8/index.php
- resolucoes/2ano-matutino/andreybonfim/parte2/q8/resposta.php
- resolucoes/2ano-matutino/andreybonfim/parte3/q1/index.php
- resolucoes/2ano-matutino/andreybonfim/parte3/q2/index.php
- resolucoes/2ano-matutino/andreybonfim/parte3/q3/index.php
- resolucoes/2ano-matutino/andreybonfim/parte3/q4/index.php
- resolucoes/2ano-matutino/andreybonfim/parte4/q1/index.php
- resolucoes/2ano-matutino/andreybonfim/parte4/q3/index.php
Finalizadas as questões: P1 - Q2 E Q7   P2 - Q1, Q2, Q6 E Q8   P3 - Q1, Q2, Q3 E Q4   P4 - Q1 E Q3.
> Entrega final da Lista de Exercícios - Andrey Bonfim

- resolucoes/3ano-matutino/geovana-porto/parte1/q2/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte1/q2/index.php
- resolucoes/3ano-matutino/geovana-porto/parte1/q3/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte1/q3/index.php
- resolucoes/3ano-matutino/geovana-porto/parte2/q2/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte2/q2/index.php
- resolucoes/3ano-matutino/geovana-porto/parte2/q3/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte2/q3/index.php
- resolucoes/3ano-matutino/geovana-porto/parte2/q7/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte2/q7/index.php
- resolucoes/3ano-matutino/geovana-porto/parte2/q8/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte2/q8/index.php
- resolucoes/3ano-matutino/geovana-porto/parte3/q1/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte3/q1/index.php
- resolucoes/3ano-matutino/geovana-porto/parte3/q3/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte3/q3/index.php
- resolucoes/3ano-matutino/geovana-porto/parte3/q4/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte3/q4/index.php
- resolucoes/3ano-matutino/geovana-porto/parte3/q5/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte3/q5/index.php
- resolucoes/3ano-matutino/geovana-porto/parte4/q1/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte4/q1/index.php
- resolucoes/3ano-matutino/geovana-porto/parte4/q3/estilo.css
- resolucoes/3ano-matutino/geovana-porto/parte4/q3/index.php
- Parte 1: 2, 3
- Parte 2: 2, 3, 7, 8
- Parte 3: 1, 3, 4, 5
- Parte 4: 1, 3
> Entrega final da lista de exercícios - [GEOVANA PORTO ROCHA]

- resolucoes/2ano-vespertino/jamylle-campos/parte1/q1/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte1/q1/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte1/q2/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte1/q2/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q1/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q1/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q2/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q2/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q6/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q6/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q8/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte2/q8/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q10/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q10/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q3/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q3/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q4/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q4/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q7/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte3/q7/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte4/q1/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte4/q1/index.php
- resolucoes/2ano-vespertino/jamylle-campos/parte4/q3/estilo.css
- resolucoes/2ano-vespertino/jamylle-campos/parte4/q3/index.php
Questões que fiz da:
Parte 1- 1 e 2
Parte 2- 1,2,6,8
Parte3- 3,4,7,10
Parte 4 - 1,3
> Resolução das questões da lista, feitas por: Jamylle Campos Silva

- resolucoes/2ano-vespertino/gleicielle meira/parte1/q1/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte1/q1/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte1/q3/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte1/q3/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q1/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q1/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q2/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q2/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q7/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q7/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q8/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte2/q8/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q1/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q1/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q2/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q2/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q3/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q3/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q4/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte3/q4/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte4/q1/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte4/q1/index.php
- resolucoes/2ano-vespertino/gleicielle meira/parte4/q3/estilo.css
- resolucoes/2ano-vespertino/gleicielle meira/parte4/q3/index.php
Realizei as atividades em outra pasta, e passei os arquivos para este repositório.
As seguintes questões realizadas:
parte1- questão 1 e 3.
parte2 - questão 1, 2, 7 e 8.
parte 3- questão 1, 2 , 3 e 4.
parte 4- questão 1 e 3.
> RESOLUÇÃO DA LISTA POR GLEICIELLE NETO MEIRA.

- resolucoes/2ano-matutino/Luciane/parte1/q10/estilo.css
- resolucoes/2ano-matutino/Luciane/parte1/q10/index.php
- resolucoes/2ano-matutino/Luciane/parte1/q8/estilo.css
- resolucoes/2ano-matutino/Luciane/parte1/q8/index.php
- resolucoes/2ano-matutino/Luciane/parte2/q1/estilo.css
- resolucoes/2ano-matutino/Luciane/parte2/q1/index.php
- resolucoes/2ano-matutino/Luciane/parte2/q10/estilo.css
- resolucoes/2ano-matutino/Luciane/parte2/q10/index.php
- resolucoes/2ano-matutino/Luciane/parte2/q3/estilo.css
- resolucoes/2ano-matutino/Luciane/parte2/q3/index.php
- resolucoes/2ano-matutino/Luciane/parte2/q6/estilo.css
- resolucoes/2ano-matutino/Luciane/parte2/q6/index.php
- resolucoes/2ano-matutino/Luciane/parte3/q1/estilo.css
- resolucoes/2ano-matutino/Luciane/parte3/q1/index.php
- resolucoes/2ano-matutino/Luciane/parte3/q2/estilo.css
- resolucoes/2ano-matutino/Luciane/parte3/q2/index.php
- resolucoes/2ano-matutino/Luciane/parte3/q3/estilo.css
- resolucoes/2ano-matutino/Luciane/parte3/q3/index.php
- resolucoes/2ano-matutino/Luciane/parte3/q4/estilo.css
- resolucoes/2ano-matutino/Luciane/parte3/q4/index.php
- resolucoes/2ano-matutino/Luciane/parte4/q1/estilo.css
- resolucoes/2ano-matutino/Luciane/parte4/q1/index.php
- resolucoes/2ano-matutino/Luciane/parte4/q3/estilo.css
- resolucoes/2ano-matutino/Luciane/parte4/q3/index.php
- Parte 1: 8, 10.
- Parte 2: 1, 3, 6, 10.
- Parte 3: 1, 2, 3, 4.
- Parte 4: 1, 3.
> Entrega final da Lista de Exercícios - [LUCIANE A. MEIRA DOS SANTOS]

- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/estilo.css
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte1/q3/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte1/q8/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte2/q2/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte2/q3/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte2/q7/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte2/q8/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte3/q2/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte3/q3/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte3/q4/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte3/q5/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte4/q1/index.php
- resolucoes/3ano-matutino/Jose_Vitor_Castro_Moreira/parte4/q3/index.php
Quesões Resolvidas:
Parte 1: 
Questão 3.
Questão 8.
Parte 2: 
Questão 2.
Questão 3.
Questão 7.
Questão 8.
Parte 3: 
Questão 2.
Questão 3.
Questão 4.
Questão 5.
Parte 4: 
Questão 1.
Questão 3.
> Resolução da Lista de Exercício por José Vitor

- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte1/q1/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte1/q1/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte1/q2/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte1/q2/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q1/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q1/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q3/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q3/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q7/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q7/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q8/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte2/q8/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q1/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q1/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q2/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q2/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q4/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q4/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q6/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte3/q6/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte4/q1/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte4/q1/index.php
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte4/q3/estilo.css
- resolucoes/2ano-vespertino/PauloHenryLimaBomfim/parte4/q3/index.php
2° ano vespertino
Parte 1: Q1 e Q2
Parte 2: Q1, Q3, Q7 e Q8
Parte 3: Q1, Q2, Q4 e Q6
Parte 4: Q1 e Q3
> Resolução da lista de exercícios por Paulo Henry Lima Bomfim 

- resolucoes/3ano-vespertino/Diego Morais/parte1/q2/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte1/q2/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte1/q3/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte1/q3/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte2/q1/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte2/q1/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte2/q3/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte2/q3/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte2/q4/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte2/q4/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte2/q5/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte2/q5/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte3/q2/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte3/q2/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte3/q3/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte3/q3/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte3/q4/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte3/q4/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte4/q1/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte4/q1/index.php
- resolucoes/3ano-vespertino/Diego Morais/parte4/q3/estilo.css
- resolucoes/3ano-vespertino/Diego Morais/parte4/q3/index.php
Parte 1: 2,3
Parte 2: 1,3,4,5
Parte 3: 2,3,4
Parte 4: 1,3
> Entrega Final da Lista de Exercício - [Diego Silva de Morais]

- resolucoes/2ano-vespertino/guilherme/estilo.css
- resolucoes/2ano-vespertino/guilherme/parte1/q1/index.php
- resolucoes/2ano-vespertino/guilherme/parte1/q1/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte1/q3/index.php
- resolucoes/2ano-vespertino/guilherme/parte1/q3/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte2/q2/index.php
- resolucoes/2ano-vespertino/guilherme/parte2/q2/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte2/q4/index.php
- resolucoes/2ano-vespertino/guilherme/parte2/q4/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte2/q6/index.php
- resolucoes/2ano-vespertino/guilherme/parte2/q6/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte2/q7/index.php
- resolucoes/2ano-vespertino/guilherme/parte2/q7/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte3/q1/index.php
- resolucoes/2ano-vespertino/guilherme/parte3/q1/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte3/q2/index.php
- resolucoes/2ano-vespertino/guilherme/parte3/q2/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte3/q5/index.php
- resolucoes/2ano-vespertino/guilherme/parte3/q5/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte3/q7/index.php
- resolucoes/2ano-vespertino/guilherme/parte3/q7/resposta.php
- resolucoes/2ano-vespertino/guilherme/parte4/q1/index.php
- resolucoes/2ano-vespertino/guilherme/parte4/q3/index.php
Questões feitas:
Parte 1: q1, q3
Parte 2: q2, q4, q6, q7
Parte 3: q1, q2, q5, q7
Parte 4: q1, q3
> Entrega final da Lista de Exercícios - Guilherme Nunes Cangussu

- resolucoes/2ano-vespertino/Jamyle Martins/parte1/q4/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte1/q4/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte1/q7/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte1/q7/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q1/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q1/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q2/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q2/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q8/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q8/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q8/receber.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q9/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte2/q9/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q1/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q1/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q2/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q2/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q3/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q3/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q4/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte3/q4/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte4/q1/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte4/q1/index.php
- resolucoes/2ano-vespertino/Jamyle Martins/parte4/q3/estilo.css
- resolucoes/2ano-vespertino/Jamyle Martins/parte4/q3/index.php
- parte 1: 4,7
- parte 2: 1,2,8,9
- parte 3: 1,2,3,4
- parte 4: 1,3
> Entrega da lista de exercícios - Jamyle Martins

- resolucoes/2ano-matutino/davi-azevedo/parte1/q1/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte1/q1/q1.css
- resolucoes/2ano-matutino/davi-azevedo/parte1/q2/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte1/q2/q2.css
- resolucoes/2ano-matutino/davi-azevedo/parte2/q1/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte2/q1/q1.css
- resolucoes/2ano-matutino/davi-azevedo/parte2/q2/estilo.css
- resolucoes/2ano-matutino/davi-azevedo/parte2/q2/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte2/q2/resposta.php
- resolucoes/2ano-matutino/davi-azevedo/parte2/q5/estilo.css
- resolucoes/2ano-matutino/davi-azevedo/parte2/q5/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte2/q5/resposta.php
- resolucoes/2ano-matutino/davi-azevedo/parte2/q6/estilo.css
- resolucoes/2ano-matutino/davi-azevedo/parte2/q6/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte2/q6/resposta.php
- resolucoes/2ano-matutino/davi-azevedo/parte3/q1/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte3/q1/q1.css
- resolucoes/2ano-matutino/davi-azevedo/parte3/q2/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte3/q2/q2.css
- resolucoes/2ano-matutino/davi-azevedo/parte3/q3/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte3/q3/q3.css
- resolucoes/2ano-matutino/davi-azevedo/parte3/q4/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte3/q4/q4.css
- resolucoes/2ano-matutino/davi-azevedo/parte4/q1/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte4/q1/q1.css
- resolucoes/2ano-matutino/davi-azevedo/parte4/q1/receber.php
- resolucoes/2ano-matutino/davi-azevedo/parte4/q3/index.php
- resolucoes/2ano-matutino/davi-azevedo/parte4/q3/q3.css
- resolucoes/2ano-matutino/davi-azevedo/parte4/q3/receber1.php
Parte 1: 1, 2
Parte 2: 1, 2, 5, 6
Parte 3: 1, 2, 3, 4
Parte 4: 1, 3
> Entrega Final da lista de exercícios - DAVI ARIEL VIEIRA NERIS AZEVEDO

- resolucoes/2ano-matutino/viniciusDourado/parte1/q10/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte1/q10/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte1/q10/resposta.php
- resolucoes/2ano-matutino/viniciusDourado/parte1/q3/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte1/q3/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte2/q1/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte2/q1/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte2/q3/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte2/q3/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte2/q4/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte2/q4/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte2/q5/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte2/q5/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte2/q5/resposta.php
- resolucoes/2ano-matutino/viniciusDourado/parte3/q1/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte3/q1/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte3/q3/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte3/q3/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte3/q5/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte3/q5/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte3/q5/resposta.php
- resolucoes/2ano-matutino/viniciusDourado/parte3/q8/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte3/q8/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte4/q1/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte4/q1/index.php
- resolucoes/2ano-matutino/viniciusDourado/parte4/q3/estilo.css
- resolucoes/2ano-matutino/viniciusDourado/parte4/q3/index.php
sendo as da 1º parte :  3 e 10.
2º parte: 1 , 3 , 4 e 5.
3º parte: 1, 3, 5 e 8.
4º parte: 1 e 3.
> final da Lista de Exercícios - Vinícius Dourado

- resolucoes/3ano-vespertino/victorkayk/estilo.css
- resolucoes/3ano-vespertino/victorkayk/parte1/q10/index.php
- resolucoes/3ano-vespertino/victorkayk/parte1/q8/index.php
- resolucoes/3ano-vespertino/victorkayk/parte2/q10/index.php
- resolucoes/3ano-vespertino/victorkayk/parte2/q4/index.php
- resolucoes/3ano-vespertino/victorkayk/parte2/q5/index.php
- resolucoes/3ano-vespertino/victorkayk/parte2/q8/index.php
- resolucoes/3ano-vespertino/victorkayk/parte3/q1/index.php
- resolucoes/3ano-vespertino/victorkayk/parte3/q10/index.php
- resolucoes/3ano-vespertino/victorkayk/parte3/q5/index.php
- resolucoes/3ano-vespertino/victorkayk/parte3/q8/index.php
- resolucoes/3ano-vespertino/victorkayk/parte4/q1/index.php
- resolucoes/3ano-vespertino/victorkayk/parte4/q2/index.php
- Parte 1: 8, 10;
- Parte 2: 4, 5, 8, 10;
- Parte 3: 1, 5, 8, 10;
- Parte 4: 1, 2;
> Entrega final da Lista de Exercícios - Victor Kayk da Silva

- resolucoes/3ano-vespertino/thiago-gentil/parte1/q1/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte1/q2/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte2/q1/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte2/q2/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte2/q3/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte2/q4/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte3/q1/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte3/q2/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte3/q3/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte3/q4/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte4/q1/index.php
- resolucoes/3ano-vespertino/thiago-gentil/parte4/q3/index.php
Parte 1: 1 e 2
Parte 2: 1, 2, 3 e 4
Parte 3: 1, 2, 3 e 4
Parte 4: 1 e 3
<p align="center">
</p>
> Entrega final da Lista de Exercícios - Thiago Gentil Santos Fernandes

- resolucoes/2ano-matutino/Riquelme/parte1/q6/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte1/q6/index.php
- resolucoes/2ano-matutino/Riquelme/parte1/q7/index.php
- resolucoes/2ano-matutino/Riquelme/parte2/q1/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte2/q1/index.php
- resolucoes/2ano-matutino/Riquelme/parte2/q2/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte2/q2/index.php
- resolucoes/2ano-matutino/Riquelme/parte2/q4/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte2/q4/index.php
- resolucoes/2ano-matutino/Riquelme/parte2/q8/index.php
- resolucoes/2ano-matutino/Riquelme/parte3/q1/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte3/q1/index.php
- resolucoes/2ano-matutino/Riquelme/parte3/q2/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte3/q2/index.php
- resolucoes/2ano-matutino/Riquelme/parte3/q4/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte3/q4/index.php
- resolucoes/2ano-matutino/Riquelme/parte3/q8/index.php
- resolucoes/2ano-matutino/Riquelme/parte4/q1/index.php
- resolucoes/2ano-matutino/Riquelme/parte4/q2/estilo.css
- resolucoes/2ano-matutino/Riquelme/parte4/q2/index.php
Questões respondidas
- Parte 1: 6,7
- Parte 2: 1,2,4,8
- Parte 3: 1,2,4,8
- Parte 4: 1,2
> Entrega final da Lista de Exercícios - João Riquelme Coqueiro Oliveira

- resolucoes/2ano-matutino/LauandaNobre/parte1/q10/JurosCompostos.php
- resolucoes/2ano-matutino/LauandaNobre/parte1/q7/fisica.php
- resolucoes/2ano-matutino/LauandaNobre/parte1/style.css
- resolucoes/2ano-matutino/LauandaNobre/parte2/q10/diadasemana.php
- resolucoes/2ano-matutino/LauandaNobre/parte2/q2/energia.php
- resolucoes/2ano-matutino/LauandaNobre/parte2/q6/triangulos.php
- resolucoes/2ano-matutino/LauandaNobre/parte2/q9/clima.php
- resolucoes/2ano-matutino/LauandaNobre/parte2/style.css
- resolucoes/2ano-matutino/LauandaNobre/parte3/q2/tabuada.php
- resolucoes/2ano-matutino/LauandaNobre/parte3/q3/numerospares.php
- resolucoes/2ano-matutino/LauandaNobre/parte3/q6/segundos.php
- resolucoes/2ano-matutino/LauandaNobre/parte3/q7/distribuicao.php
- resolucoes/2ano-matutino/LauandaNobre/parte3/style.css
- resolucoes/2ano-matutino/LauandaNobre/parte4/q1/frutas.php
- resolucoes/2ano-matutino/LauandaNobre/parte4/q3/pizzaria.php
- resolucoes/2ano-matutino/LauandaNobre/parte4/style.css
Entrega da lista de exercícios [LAUANDA SANTOS NOBRE]
-Parte 1: 7 e 10
-Parte 2: 2, 6, 9 e 10
-Parte 3: 2, 3, 6 e 7
-Parte 4: 1 e 2
> Entrega da lista de exercícios [LAUANDA SANTOS NOBRE]  

- resolucoes/3ano-vespertino/WendelCosta/parte1/q1/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte1/q1/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte1/q4/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte1/q4/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte2/q1/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte2/q1/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte2/q2/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte2/q2/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte2/q3/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte2/q3/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte2/q4/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte2/q4/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte3/q1/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte3/q1/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte3/q2/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte3/q2/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte3/q3/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte3/q3/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte3/q4/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte3/q4/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte4/q1/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte4/q1/index.php
- resolucoes/3ano-vespertino/WendelCosta/parte4/q3/estilo.css
- resolucoes/3ano-vespertino/WendelCosta/parte4/q3/index.php
Parte 1 -> 1 e 4; Parte 2  -> 1,2,3,4; Parte 3 -> 1,2,3,4; Parte 4 -> 1,3
> Entrega final da Lista de Exercícios - Wendel dos Santos Costa

- resolucoes/3ano-vespertino/modelo-resposta/parte1/q1/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte1/q1/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte1/q6/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte1/q6/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q1/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q1/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q2/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q2/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q8/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q8/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q9/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte2/q9/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q1/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q1/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q2/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q2/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q3/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q3/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q4/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte3/q4/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte4/q1/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte4/q1/index.php
- resolucoes/3ano-vespertino/modelo-resposta/parte4/q3/estilo.css
- resolucoes/3ano-vespertino/modelo-resposta/parte4/q3/index.php
Parte 1:  questões 1 e 6;
Parte 2: questões 1, 2, 8, 9
Parte 3: questões  1,2,3,4
Parte 4: 1 e 3
> Entrega final da Lista de Exercícios - [LETICIA EVELIN VIEIRA SANTOS]

- resolucoes/3ano-matutino/Abner da Silva Cunha/parte1/q1/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte1/q1/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte1/q2/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte1/q2/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte2/q1/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte2/q1/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte2/q3/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte2/q3/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte2/q5/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte2/q5/formulario-resposta.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte3/q2/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte3/q2/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte3/q3/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte3/q3/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte3/q7/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte3/q7/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte4/q1/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte4/q1/index.php
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte4/q2/estilo.css
- resolucoes/3ano-matutino/Abner da Silva Cunha/parte4/q2/index.php
- Parte 1: 1,2
- Parte 2: 1,3,5,6
- Parte 3: 2,3,4,7
- Parte 4: 1,2
> Entrega final da Lista de Exercícios - Abner da Silva Cunha

- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte1/q2/estilo.css
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte1/q2/formulario-resposta.php
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte1/q7/estilo.css
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte1/q7/formulario-resposta.php
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte2/q4/estilo.css
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte2/q4/formulario-resposta.php
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte2/q8/estilo.css
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte2/q8/formulario-resposta.php
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte2/q9/estilo.css
- resolucoes/3ano-matutino/Fatima-Vitoria-Leite-Lobo/parte2/q9/formulario-resposta.php
**Parte 1:**
- Questão 2
- Questão 7
**Parte 2:**
- Questão 4
- Questão 8
- Questão 9
> Entrega final da Lista de Exercícios - [Fátima Vitória Leite Lôbo]

- resolucoes/2ano-matutino/IvoCarlos/estilo.css
- resolucoes/2ano-matutino/IvoCarlos/parte1/q3/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte1/q8/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte2/q2/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte2/q5/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte2/q6/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte2/q8/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte3/q2/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte3/q3/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte3/q6/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte3/q7/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte4/q2/index.php
- resolucoes/2ano-matutino/IvoCarlos/parte4/q3/index.php
***Questões respondidas
-Parte 1: 3,8
-Parte 2: 2,5,6,8
-Parte 3: 2,3,6,7
-Parte 4: 2,3
> Entrega final da Lista de Exercícios- Ivo Carlos Moreira Lima

- resolucoes/2ano-vespertino/danilocm/parte1/q1/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte1/q1/index.php
- resolucoes/2ano-vespertino/danilocm/parte1/q1/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte1/q2/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte1/q2/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte1/q2/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte3/q1/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte3/q1/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte3/q1/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte3/q2/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte3/q2/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte3/q2/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte3/q3/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte3/q3/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte3/q3/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte3/q4/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte3/q4/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte3/q4/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte4/q1/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte4/q1/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte4/q1/resposta.php
- resolucoes/2ano-vespertino/danilocm/parte4/q3/estilo.css
- resolucoes/2ano-vespertino/danilocm/parte4/q3/formulario.php
- resolucoes/2ano-vespertino/danilocm/parte4/q3/resposta.php
Fiz a questão 1 e 2 da parte 1
Fiz a questão 1 a 4 da parte 3
Fiz a questão 1 e 3 da parte 3
> Entergra Final Danilo CerqueiraDescrição

- resolucoes/3ano-matutino/KauaDosSantosLima/parte1/q1/estilo.css
- resolucoes/3ano-matutino/KauaDosSantosLima/parte1/q1/index.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte1/q1/resposta.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte1/q2/estilo.css
- resolucoes/3ano-matutino/KauaDosSantosLima/parte1/q2/index.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte1/q2/resposta.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q1/estilo.css
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q1/index.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q1/resposta.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q3/estilo.css
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q3/index.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q3/resposta.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q7/estilo.css
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q7/index.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q7/resposta.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q8/estilo.css
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q8/index.php
- resolucoes/3ano-matutino/KauaDosSantosLima/parte2/q8/resposta.php
Parte1 - 1 e 2
Parte2 - 1, 3, 7 e 8
Parte3 - 0
Parte4 - 0
> Entrega final da Lista de Exercícios - Kauã dos Santos Lima

- resolucoes/3ano-matutino/tauane_carol/parte1/q1/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte1/q1/index.php
- resolucoes/3ano-matutino/tauane_carol/parte1/q5/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte1/q5/index.php
- resolucoes/3ano-matutino/tauane_carol/parte1/q5/receber1.php
- resolucoes/3ano-matutino/tauane_carol/parte2/q2/index.php
- resolucoes/3ano-matutino/tauane_carol/parte2/q6/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte2/q6/index.php
- resolucoes/3ano-matutino/tauane_carol/parte2/q7/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte2/q7/index.php
- resolucoes/3ano-matutino/tauane_carol/parte2/q8/index.php
- resolucoes/3ano-matutino/tauane_carol/parte3/q2/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte3/q2/index.php
- resolucoes/3ano-matutino/tauane_carol/parte3/q3/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte3/q4/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte3/q4/index.php
- resolucoes/3ano-matutino/tauane_carol/parte3/q8/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte3/q8/index.php
- resolucoes/3ano-matutino/tauane_carol/parte4/q1/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte4/q1/index.php
- resolucoes/3ano-matutino/tauane_carol/parte4/q2/estilo.css
- resolucoes/3ano-matutino/tauane_carol/parte4/q2/index.php
**** QUESTÕES RESPONDIDAS:
* Parte 1: 1 e 5;
* Parte 2: 2, 6, 7 e 8;
* Parte 3: 2, 3, 4 e 8;
* Parte 4: 1 e 2
> Entrega final da Lista de Exercícios - [ TAUANE CAROL ]

- resolucoes/3ano-matutino/Rian_Carlo/parte1/q1/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte1/q1/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte1/q5/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte1/q5/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte1/q5/receber1.php
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q2/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q2/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q6/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q6/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q7/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q7/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q8/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte2/q8/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q2/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q2/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q3/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q3/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q4/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q4/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q8/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte3/q8/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte4/q1/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte4/q1/index.php
- resolucoes/3ano-matutino/Rian_Carlo/parte4/q2/estilo.css
- resolucoes/3ano-matutino/Rian_Carlo/parte4/q2/index.php
--questões respondidas:
* parte 1: 1 e 5;
* parte 2: 2, 6, 7 e 8;
* parte 3: 2, 3, 4 e 8;
* parte 4: 1 e 2:
> Entrega final da Lista de Exercícios - [ RIAN SANTOS ]

- resolucoes/2ano-matutino/vitor-souza-dourado/parte1/q1/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte1/q2/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte2/q1/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte2/q5/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte2/q6/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte2/q8/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte3/q10/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte3/q10/resposta.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte3/q2/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte3/q3/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte3/q7/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte3/q7/resposta.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte4/q1/estilo.css
- resolucoes/2ano-matutino/vitor-souza-dourado/parte4/q1/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte4/q1/resposta.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte4/q3/estilo.css
- resolucoes/2ano-matutino/vitor-souza-dourado/parte4/q3/index.php
- resolucoes/2ano-matutino/vitor-souza-dourado/parte4/q3/resposta.php
Parte 1  -  1 2;
parte 2 - 1, 5, 6, 8;
parte 3 - 2, 3, 7, 10;
parte 4 - 1 e 3;
> Lista de exercícios-Vítor Souza Dourado

- resolucoes/2ano-matutino/edmilsonjunior/parte1/q1/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte1/q1/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte1/q4/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte1/q4/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q1/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q1/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q2/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q2/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q3/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q3/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q3/resposta.php
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q5/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q5/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte2/q5/resposta.php
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q1/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q1/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q2/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q2/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q3/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q3/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q4/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte3/q4/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte4/q1/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte4/q1/index.php
- resolucoes/2ano-matutino/edmilsonjunior/parte4/q3/estilo.css
- resolucoes/2ano-matutino/edmilsonjunior/parte4/q3/index.php
Q1 - Q4, parte 1
Q1 - Q2 - Q3 - Q5, parte 2
Q1 - Q2 - Q3 - Q4, parte 3
Q1 - Q3, parte 4
> Lista de exercicios - Edmilson Silva Costa Júnior

- resolucoes/3ano-vespertino/joao_venancio/parte1/q2/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte1/q2/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte1/q2/resposta.php
- resolucoes/3ano-vespertino/joao_venancio/parte1/q5/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte1/q5/formulario.php
- resolucoes/3ano-vespertino/joao_venancio/parte2/q2/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte2/q2/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte2/q2/receber.php
- resolucoes/3ano-vespertino/joao_venancio/parte2/q3/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte2/q3/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte2/q4/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte2/q4/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte2/q7/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte2/q7/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte3/q1/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte3/q2/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte3/q2/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte3/q4/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte3/q4/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte3/q4/resposta.php
- resolucoes/3ano-vespertino/joao_venancio/parte3/q6/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte3/q6/index.php
- resolucoes/3ano-vespertino/joao_venancio/parte4/q1/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte4/q1/formulario.php
- resolucoes/3ano-vespertino/joao_venancio/parte4/q3/estilo.css
- resolucoes/3ano-vespertino/joao_venancio/parte4/q3/index.php
Parte 1 --- q2,q5
Parte 2 ----- q2,q3,q4,q7
Parte 3 --- q1,q2,q4,q6
Parte 4 -- q1,q3
> resolucaoJoaoVenancio
